{% set name = "dunamai" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6abfeb91768caea59d65a4989cec49472fa66ee04dcd6a5c9f92ebc019926a93

build:
  number: 0
  noarch: python
  entry_points:
    - dunamai = dunamai.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.5,<4.0
  run:
    - python >=3.5,<4.0
    - setuptools >=8.0

test:
  imports:
    - dunamai
  commands:
    - pip check
    - dunamai --help
  requires:
    - pip

about:
  home: https://github.com/mtkennerly/dunamai
  summary: Dynamic version generation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
