{% set name = "dunamai" %}
{% set version = "1.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc3dc52c69eb14c5374e3ce9cb68413e143f7e5983ab0b55f0c099cd36572482

build:
  number: 0
  noarch: python
  entry_points:
    - dunamai = dunamai.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.5
  run:
    - importlib-metadata >=1.6.0
    - packaging >=20.9
    - python >=3.5

test:
  imports:
    - dunamai
  commands:
    - pip check
    - dunamai --help
  requires:
    - pip

about:
  home: https://github.com/mtkennerly/dunamai
  summary: Dynamic version generation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
