{% set name = "dunamai" %}
{% set version = "1.24.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3aa3348f77242da8628b23f11e89569343440f0f912bcef32a1fa891cf8e7215

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - dunamai = dunamai.__main__:main

requirements:
  host:
    - pip
    - poetry-core 1.5
    - python
    - setuptools
    - wheel
  run:
    - importlib-metadata >=1.6.0  # [py<38]
    - packaging >=20.9
    - python

test:
  imports:
    - dunamai
  requires:
    - pip
  commands:
    - pip check
    - dunamai --help

about:
  home: https://github.com/mtkennerly/dunamai
  dev_url: https://github.com/mtkennerly/dunamai
  doc_url: https://github.com/mtkennerly/dunamai
  summary: Dynamic versioning library and CLI
  description: |
    Dunamai is a Python library and command line tool for producing dynamic, standards-compliant version strings, derived from tags in your version control system. This facilitates uniquely identifying nightly or per-commit builds in continuous integration and releasing new versions of your software simply by creating a tag.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - BastianZim
